name: Automated builds

on:
  push:
    paths:
      - "images/**"
      - ".github/workflows/*"
  pull_request: # They will only build the containers, not push them to our registry
    paths:
      - "images/**"
      - ".github/workflows/*"
    types:
      - opened
      - edited
      - ready_for_review
      - review_requested
      - reopened
#  schedule:
#    - cron: "0 0 * * *" # nightly

jobs:
  base:
    uses: ./.github/workflows/docker-build-and-publish.yml
    with:
      image_name: "base"
    secrets: inherit

  base-app:
    needs: [base]
    strategy:
      matrix:
        platform:
          - arch: "linux/amd64"
            runner: "ubuntu-latest"
          - arch: "linux/arm64"
            runner: "ARM64"
    uses: ./.github/workflows/docker-build-and-publish.yml
    with:
      image_name: "base-app"
      base_image: "${{ needs.base.outputs.image_tag }}"
      platforms: "${{ matrix.platform.arch }}"
      runs-on: "${{ matrix.platform.runner }}"
    secrets: inherit

  apps:
    needs: [base, base-app]
    strategy:
      matrix:
        platform:
          - arch: "linux/amd64"
            runner: "ubuntu-latest"
            images:
              [
                xorg,
                pulseaudio,
                udevd,
                sunshine,
                retroarch,
                firefox,
                steam,
                pegasus,
                lutris,
                heroic-games-launcher,
              ]
          - arch: "linux/arm64"
            runner: "ARM64"
            images: [firefox]
          #- name: es-de
          #  platforms: ["linux/amd64"]
      fail-fast: false
    uses: ./.github/workflows/docker-build-and-publish.yml
    with:
      image_name: "${{ matrix.plateform.images }}"
      base_image: "${{ needs.base.outputs.image_tag }}"
      base_app_image: "${{ needs.base-app.outputs.image_tag }}"
      platforms: "${{ matrix.platform.arch }}"
      runs-on: "${{ matrix.platform.runner }}"
    secrets: inherit
